version: '3'
services:
  coordinator:
    container_name: coordinator
    build:
      context: coordinator
      dockerfile: ${DOCKERFILE}
    security_opt:
      - seccomp:unconfined
    ports:
      - ${HTTP_PORT}:80
      - ${DEBUG_PORT}:40000
    healthcheck:
      test: curl --fail -s http://localhost/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    restart: on-failure
    networks:
      - net
    volumes:
      - .:/go/src

  counter:
    build:
      context: counter
      dockerfile: ${DOCKERFILE}
    depends_on:
      - coordinator
    security_opt:
      - seccomp:unconfined
    expose:
      - 80
    restart: on-failure
    networks:
      - net
    volumes:
      - .:/go/src

networks:
  net:
    driver: bridge